id: ADD operation
inputs:
  - normalizerRef: integer
    normalizerOptions:
      min: 0
      max: 100
  - normalizerRef: integer
    normalizerOptions:
      min: 0
      max: 100
outputs:
  - normalizerRef: integer
    normalizerOptions:
      min: 0
      max: 200
hiddenLayersCounts: [ ]
strategy:
  id: identity
  options:
    minWeight: -1000
    maxWeight: 1000
training:
  expectedMaxIterations: 50
  learningRate: 0.2
